blueprint:
  name: Windows Sensor automated Thermostat
  description: Turns on and off the thermostat depending on window sensor
  domain: automation
  input:
    window_sensor:
      name: Window Sensor
      description: This sensor will be used to turn on/off the thermostat.
      selector:
        entity:
          domain: binary_sensor
          device_class: door
    target_hvac:
      name: Thermostat
      description: Thermostat to turn on/off.
      selector:
        target:
          entity:
            domain: climate
            
trigger:
  platform: state
  entity_id: !input window_sensor
  
action:
  - if:
      - condition: state
        entity_id: !input window_sensor
        state: "on"
    then:
      domain: climate
      entity_id: !input target_hvac
      type: set_hvac_mode
      hvac_mode: "off"
    else:
      domain: climate
      entity_id: !input target_hvac
      type: set_hvac_mode
      hvac_mode: auto
mode: single
